export const customFormApi = [
  {
    id: "fullName",
    label: "Full Name",
    type: "text",
    regex: "^[A-Za-z ]+$",
    placeholder: "John Doe",
    errorMessage: "Enter valid name with alphabet characters",
    required: true,
    values: "",
  },
  {
    id: "email",
    label: "Email",
    type: "text",
    regex: "^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+.[A-Za-z]{2,}$",
    errorMessage: "Enter valid email in proper format",
    placeholder: "johndoe@gmail.com",
    required: true,
    values: "",
  },
  {
    id: "contact",
    label: "Phone",
    type: "text",
    regex: "^[6-9][0-9]{9}$",
    errorMessage: "Enter a valid 10-digit phone number starting with 6-9",
    placeholder: "9955664477",
    required: true,
    values: "",
  },
  {
    id: "address",
    label: "Address",
    type: "array",
    fields: [
      {
        id: "streets",
        label: "Building & Street Name",
        type: "text",
        placeholder: "Building & Street Name",
        required: true,
        values: "",
      },
      {
        id: "city",
        label: "City Name",
        type: "text",
        placeholder: "City",
        regex: "^[A-Za-z]+$",
        errorMessage: "Enter valid name with alphabet characters",
        required: true,
        values: "",
      },
      {
        id: "pincode",
        label: "Pincode",
        type: "text",
        placeholder: "Pincode",
        required: true,
        regex: "^[1-9][0-9]{5}$",
        errorMessage: "Enter a valid 6-digit pincode",
        values: "",
      },
    ],
  },
  {
    id: "employmentCategoy",
    label: "Select Current Status",
    type: "select",
    options: ["Unemployed", "Self-Employed", "Employed"],
    required: true,
    values: "",
  },

  {
    id: "drivingLicenseDoc",
    label: "Do You have Driving License ?",
    type: "select",
    required: true,
    options: ["Yes", "No"],
    values: "",
  },
  {
    id: "drivingLicense",
    label: "Driving License",
    type: "text",
    regex: "^[A-Z]{2}[0-9]{13,14}$",
    errorMessage: "Enter a valid Driving License Number",
    placeholder: "Enter Driving License Number",
    requiredIf: {
      id: "drivingLicenseDoc",
      status: "Yes",
    },
    values: "",
  },
];
